language: python
python: 3.5
cache:
  directories:
    - ~/.cache/pip
install:
  - pip install -r requirements/ci.pip
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=docs
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=project-develop
  - TOXENV=project-docs
  - TOXENV=project-flake8
  - TOXENV=project-isort
  - TOXENV=project-manifest
  - TOXENV=project-pep257
  - TOXENV=project-py27
  - TOXENV=project-py35
services:
  - postgresql
addons:
  postgresql: "9.3"
script:
  - make test
sudo: false
notifications:
  slack:
    secure: ic70R8NJdSRtGvpOS2xJzegUTD/vVzgvz47rGmBCt2d0pW01IUA1pZ/KGAMj17F0dqhuv/RKlXex9TagHzf0AyEWOiFj5cr/zJyWKxtXsMhzJnpGwltMoE44lHfNW79xHXyEaRDRPdo1NwVvtDG4KYAocseMHMhCPhuB1TJohdo=
